[package]
name = "mcrs"
version = "0.0.1"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["full"] }
tokio-macros = "2.5.0"
serde_json = "1.0.135"
log = "0.4.22"
